```yaml
name: Tuxido Assistant CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-assistant:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Dev Assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python dev_assistant/dev_assistant.py
```
